### ISSUE TITLE
i have some problems

### ISSUE THREAD

**Issue by tiannahaha** [TylerDodds/DeformableSnowRendering#1]
Could not create asset from Assets/Snow/Textures/HeightMapTest/Snow_Height_Map_Mask_Blended_Example_1_Height.png:File could not be read
Could not create asset from Assets/Snow/Textures/HeightMapTest/Snow_Packed_Detail_Map_Sparkle_Test_Packed.png:File could not be read
.....
and so many
seems like all of the textures have the same problem
how can i solve the problem?

**Comment by TylerDodds** [comment]
Textures are stored using [Git LFS](https://git-lfs.github.com/), so first make sure that you have that installed, then clone the repository so that the textures can be properly pulled. They will not be found if you get the project through `Code > Download ZIP`.

I've updated `README.md` with this information as well.

**Comment by tiannahaha** [comment]
Thank you very much for your reply and patient explanation, and I wish you all the best！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TylerDodds/DeformableSnowRendering"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 凌晨0:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TylerDodds/DeformableSnowRendering] i have some problems (Issue #1)





 
Textures are stored using Git LFS, so first make sure that you have that installed, then clone the repository so that the textures can be properly pulled. They will not be found if you get the project through Code &gt; Download ZIP.
 
I've updated README.md with this information as well.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tiannahaha** [comment]
i have already installed the Git LFS，and copied the modified version of the HDRP package into the Packages folder, when i open the project and run ,the following error occurs


What should I do?（i look forward to your reply ^_^）
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TylerDodds/DeformableSnowRendering"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月12日(星期六) 中午11:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TylerDodds/DeformableSnowRendering] i have some problems (Issue #1)





 
Closed #1.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
